[package]
name = "astro-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde       = { version = "1", default-features = false, features = ["derive", "alloc"] }
serde_json  = { version = "1", default-features = false, features = ["alloc"] }
chrono      = { version = "0.4", default-features = false, features = ["alloc"] }
chrono-tz   = { version = "0.9", default-features = false }

[build-dependencies]
cc = "1"
